(function(){
"use strict";
const STORAGE_KEY="basmi_phising_reports",DETAIL_KEY="basmi_phising_detail",NETCRAFT_URL="https://report.netcraft.com/report";
const $=id=>document.getElementById(id);
function loadReports(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(d)?d:[]}catch{return[]}}
function loadDetail(){try{return localStorage.getItem(DETAIL_KEY)||""}catch{return""}}
function urlsOnly(){return loadReports().map(x=>x&&x.url).filter(Boolean)}
function emailTemplate(urls,detail){const d=detail||"URL tersebut diduga terkait aktivitas yang berpotensi merugikan atau menyesatkan pengguna. Mohon dilakukan pemeriksaan lebih lanjut.";return `Yth. Tim Aduan Konten,\n\nDengan hormat,\n\nSaya ingin melaporkan sejumlah URL yang diduga memuat atau mengarahkan pengguna ke konten yang perlu diperiksa lebih lanjut.\n\nBerikut daftar URL yang perlu diperiksa:\n\n${urls.join("\n")}\n\nMohon Tim Aduan Konten dapat melakukan pemeriksaan dan verifikasi terhadap URL tersebut, khususnya terkait kemungkinan adanya:\n\n- Promosi atau penyebaran konten yang melanggar ketentuan.\n- Tautan yang mengarahkan pengguna ke situs atau konten terkait.\n- Penyalahgunaan domain atau website pihak ketiga.\n- Halaman spam atau konten yang dibuat untuk memanipulasi hasil pencarian.\n- Konten yang berpotensi menyesatkan atau merugikan pengguna.\n\nBeberapa URL menggunakan domain yang tampaknya tidak berkaitan langsung dengan konten yang dilaporkan. Oleh karena itu, saya memohon agar turut diperiksa apakah terdapat penyisipan atau penyalahgunaan halaman untuk menampilkan konten tersebut tanpa keterkaitan dengan fungsi utama domain.\n\nKeterangan tambahan:\n${d}\n\nApabila setelah dilakukan pemeriksaan ditemukan adanya pelanggaran, mohon agar URL atau konten terkait dapat ditindaklanjuti sesuai dengan ketentuan dan peraturan yang berlaku.\n\nDemikian laporan ini saya sampaikan. Terima kasih atas perhatian dan tindak lanjut dari Tim Aduan Konten.\n\nHormat saya,\n\nPelapor`}
function copyText(text,button){navigator.clipboard.writeText(text).then(()=>{const old=button.textContent;button.textContent="✓ TERSALIN";setTimeout(()=>button.textContent=old,1200)}).catch(()=>{button.textContent="GAGAL COPY";setTimeout(()=>button.textContent="SALIN",1200)})}
function refresh(){const urls=urlsOnly(),detail=loadDetail();$("emailPreview").value=emailTemplate(urls,detail);$("reportCount").textContent=`${urls.length} URL SIAP DILAPORKAN`;$("reportStatus").textContent=urls.length?"DATA TERSEDIA DARI DASHBOARD":"BELUM ADA DATA DARI DASHBOARD";const list=$("netcraftUrls");list.innerHTML="";if(!urls.length){const e=document.createElement("div");e.className="report-empty";e.textContent="Belum ada URL. Masukkan URL di Dashboard lalu tekan PROSES URL.";list.appendChild(e);return}urls.forEach((url,i)=>{const row=document.createElement("div");row.className="report-url-row";const code=document.createElement("code");code.textContent=`${i+1}. ${url}`;const badge=document.createElement("span");badge.className="report-count";badge.textContent="READY";row.append(code,badge);list.appendChild(row)})}
$("emailTab").onclick=()=>{$("emailPanel").classList.add("active");$("netcraftPanel").classList.remove("active");$("emailTab").classList.add("active");$("netcraftTab").classList.remove("active")};
$("netcraftTab").onclick=()=>{$("netcraftPanel").classList.add("active");$("emailPanel").classList.remove("active");$("netcraftTab").classList.add("active");$("emailTab").classList.remove("active")};
$("copyEmail").onclick=()=>copyText($("emailPreview").value,$("copyEmail"));
$("copyUrls").onclick=()=>copyText(urlsOnly().join("\n"),$("copyUrls"));
$("openNetcraft").onclick=()=>{const urls=urlsOnly();if(!urls.length){alert("Belum ada URL dari Dashboard.");return}navigator.clipboard.writeText(urls.join("\n")).finally(()=>window.open(NETCRAFT_URL,"_blank","noopener,noreferrer"))};
$("refreshReports").onclick=refresh;refresh();
})();
